{% set name = "dirsync" %}
{% set version = "2.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dirsync-{{ version }}.tar.gz
  sha256: 53b557ec5b54bda19c155cd04d7bb935f8b4a74450985f22a9f555a0360570bc

build:
  entry_points:
    - dirsync = dirsync.run:from_cmdline
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - dirsync
  commands:
    - pip check
    - dirsync --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tkhyn/dirsync/
  summary: Advanced directory tree synchronisation tool
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
